<?php

namespace Database\Seeders;

use App\Models\Cuisine;
use App\Models\Restaurant;
use Illuminate\Database\Seeder;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        // Intentionally disabled (spec-019). The hard-coded San Francisco
        // restaurants below were fake seed data with invented ratings/reviews.
        // Because the controller is DB-first, that fake data was served for SF
        // while every other city hit live search — distorting results. iPop360
        // is now live-search-first for every city (cached ~30 days via SerpApi),
        // so the DB no longer needs seed restaurants. The data array is kept
        // below as a paper trail; populate real venues via `restaurants:enrich`
        // instead.
        return;
    }

    // getRestaurantsData() below is retained as a paper trail but is no longer
    // called — see run(). Original fake SF seed data.

    private function getRestaurantsData(): array
    {
        return [
            // Asian - Japanese
            [
                'name' => 'Sakura Sushi House',
                'slug' => 'sakura-sushi-house',
                'description' => 'Authentic Japanese sushi and sashimi prepared by master chef with 20 years of experience.',
                'address' => '123 Japantown Ave',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94115',
                'latitude' => 37.7851,
                'longitude' => -122.4290,
                'phone' => '(415) 555-0101',
                'website_url' => 'https://example.com/sakura',
                'price_range' => '$$$',
                'photo_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop',
                'google_rating' => 4.7,
                'google_review_count' => 2340,
                'yelp_rating' => 4.5,
                'yelp_review_count' => 1876,
                'popular_times_avg_busyness' => 72.50,
                'popularity_score' => 0.9234,
                'is_active' => true,
                'cuisines' => ['japanese'],
            ],
            [
                'name' => 'Ramen Ichiban',
                'slug' => 'ramen-ichiban',
                'description' => 'Rich tonkotsu broth simmered for 18 hours with handmade noodles and premium toppings.',
                'address' => '456 Mission St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94105',
                'latitude' => 37.7886,
                'longitude' => -122.3995,
                'phone' => '(415) 555-0102',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop',
                'google_rating' => 4.5,
                'google_review_count' => 1890,
                'yelp_rating' => 4.4,
                'yelp_review_count' => 1540,
                'popular_times_avg_busyness' => 68.30,
                'popularity_score' => 0.8512,
                'is_active' => true,
                'cuisines' => ['japanese'],
            ],
            // Asian - Chinese
            [
                'name' => 'Golden Dragon Palace',
                'slug' => 'golden-dragon-palace',
                'description' => 'Traditional Cantonese dim sum and seafood in an elegant setting since 1985.',
                'address' => '789 Grant Ave',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94108',
                'latitude' => 37.7941,
                'longitude' => -122.4078,
                'phone' => '(415) 555-0103',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop',
                'google_rating' => 4.4,
                'google_review_count' => 3210,
                'yelp_rating' => 4.3,
                'yelp_review_count' => 2890,
                'popular_times_avg_busyness' => 75.80,
                'popularity_score' => 0.8867,
                'is_active' => true,
                'cuisines' => ['chinese'],
            ],
            [
                'name' => 'Sichuan Fire',
                'slug' => 'sichuan-fire',
                'description' => 'Authentic Sichuan cuisine with fiery mapo tofu, dan dan noodles, and mouth-watering lamb dishes.',
                'address' => '321 Clement St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94118',
                'latitude' => 37.7831,
                'longitude' => -122.4630,
                'phone' => '(415) 555-0104',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=400&h=300&fit=crop',
                'google_rating' => 4.6,
                'google_review_count' => 1560,
                'yelp_rating' => 4.5,
                'yelp_review_count' => 1230,
                'popular_times_avg_busyness' => 62.40,
                'popularity_score' => 0.8145,
                'is_active' => true,
                'cuisines' => ['chinese'],
            ],
            // Asian - Thai
            [
                'name' => 'Bangkok Street Kitchen',
                'slug' => 'bangkok-street-kitchen',
                'description' => 'Vibrant Thai street food with authentic pad thai, green curry, and mango sticky rice.',
                'address' => '567 Haight St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94117',
                'latitude' => 37.7725,
                'longitude' => -122.4331,
                'phone' => '(415) 555-0105',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=400&h=300&fit=crop',
                'google_rating' => 4.5,
                'google_review_count' => 2100,
                'yelp_rating' => 4.4,
                'yelp_review_count' => 1780,
                'popular_times_avg_busyness' => 65.20,
                'popularity_score' => 0.8321,
                'is_active' => true,
                'cuisines' => ['thai'],
            ],
            // Asian - Vietnamese
            [
                'name' => 'Pho Saigon Noodle Bar',
                'slug' => 'pho-saigon-noodle-bar',
                'description' => ' steaming bowls of pho with house-made bone broth, fresh herbs, and crispy banh mi sandwiches.',
                'address' => '890 Turk St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94102',
                'latitude' => 37.7790,
                'longitude' => -122.4230,
                'phone' => '(415) 555-0106',
                'price_range' => '$',
                'photo_url' => 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400&h=300&fit=crop',
                'google_rating' => 4.6,
                'google_review_count' => 1780,
                'yelp_rating' => 4.5,
                'yelp_review_count' => 1420,
                'popular_times_avg_busyness' => 58.90,
                'popularity_score' => 0.8012,
                'is_active' => true,
                'cuisines' => ['vietnamese'],
            ],
            // Asian - Korean
            [
                'name' => 'Seoul BBQ & Grill',
                'slug' => 'seoul-bbq-grill',
                'description' => 'Premium Korean BBQ with tabletop grilling, banchan sides, and Soju cocktails.',
                'address' => '234 Geary St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94102',
                'latitude' => 37.7869,
                'longitude' => -122.4117,
                'phone' => '(415) 555-0107',
                'price_range' => '$$$',
                'photo_url' => 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=300&fit=crop',
                'google_rating' => 4.7,
                'google_review_count' => 2670,
                'yelp_rating' => 4.6,
                'yelp_review_count' => 2150,
                'popular_times_avg_busyness' => 78.40,
                'popularity_score' => 0.9178,
                'is_active' => true,
                'cuisines' => ['korean'],
            ],
            // Asian - Filipino
            [
                'name' => 'Lumpia Legend',
                'slug' => 'lumpia-legend',
                'description' => 'Home-style Filipino cooking featuring crispy lumpia, chicken adobo, sinigang, and halo-halo.',
                'address' => '456 Mission St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94105',
                'latitude' => 37.7900,
                'longitude' => -122.3970,
                'phone' => '(415) 555-0108',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=400&h=300&fit=crop',
                'google_rating' => 4.4,
                'google_review_count' => 980,
                'yelp_rating' => 4.3,
                'yelp_review_count' => 760,
                'popular_times_avg_busyness' => 48.60,
                'popularity_score' => 0.6234,
                'is_active' => true,
                'cuisines' => ['filipino'],
            ],
            // Asian - Indian
            [
                'name' => 'Taj Mahal Spice Room',
                'slug' => 'taj-mahal-spice-room',
                'description' => 'Authentic North Indian cuisine with tandoori specialties, aromatic curries, and freshly baked naan.',
                'address' => '678 Jones St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94102',
                'latitude' => 37.7865,
                'longitude' => -122.4146,
                'phone' => '(415) 555-0109',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop',
                'google_rating' => 4.5,
                'google_review_count' => 1920,
                'yelp_rating' => 4.4,
                'yelp_review_count' => 1580,
                'popular_times_avg_busyness' => 60.10,
                'popularity_score' => 0.8145,
                'is_active' => true,
                'cuisines' => ['indian'],
            ],
            // European - Italian
            [
                'name' => 'Trattoria Bella Vista',
                'slug' => 'trattoria-bella-vista',
                'description' => 'Handmade pasta and wood-fired Neapolitan pizza in a cozy North Beach setting.',
                'address' => '901 Columbus Ave',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94133',
                'latitude' => 37.8003,
                'longitude' => -122.4113,
                'phone' => '(415) 555-0110',
                'website_url' => 'https://example.com/bellavista',
                'price_range' => '$$$',
                'photo_url' => 'https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=400&h=300&fit=crop',
                'google_rating' => 4.8,
                'google_review_count' => 3450,
                'yelp_rating' => 4.7,
                'yelp_review_count' => 2890,
                'popular_times_avg_busyness' => 82.30,
                'popularity_score' => 0.9567,
                'is_active' => true,
                'cuisines' => ['italian'],
            ],
            [
                'name' => 'Pasta Fresca',
                'slug' => 'pasta-fresca',
                'description' => 'Small-batch fresh pasta made daily with seasonal sauces and local ingredients.',
                'address' => '234 Valencia St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94103',
                'latitude' => 37.7700,
                'longitude' => -122.4210,
                'phone' => '(415) 555-0111',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400&h=300&fit=crop',
                'google_rating' => 4.6,
                'google_review_count' => 1340,
                'yelp_rating' => 4.5,
                'yelp_review_count' => 1120,
                'popular_times_avg_busyness' => 55.70,
                'popularity_score' => 0.7789,
                'is_active' => true,
                'cuisines' => ['italian'],
            ],
            // European - French
            [
                'name' => 'Café Lumière',
                'slug' => 'cafe-lumiere',
                'description' => 'Classic French bistro fare with coq au vin, croque monsieur, and an extensive wine list.',
                'address' => '567 Bush St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94108',
                'latitude' => 37.7900,
                'longitude' => -122.4070,
                'phone' => '(415) 555-0112',
                'price_range' => '$$$',
                'photo_url' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
                'google_rating' => 4.6,
                'google_review_count' => 1780,
                'yelp_rating' => 4.5,
                'yelp_review_count' => 1450,
                'popular_times_avg_busyness' => 64.80,
                'popularity_score' => 0.8234,
                'is_active' => true,
                'cuisines' => ['french'],
            ],
            // European - Spanish
            [
                'name' => 'Tapas del Sol',
                'slug' => 'tapas-del-sol',
                'description' => 'Vibrant Spanish tapas with patatas bravas, gambas al ajillo, and sangria pitchers.',
                'address' => '890 Folsom St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94107',
                'latitude' => 37.7825,
                'longitude' => -122.3980,
                'phone' => '(415) 555-0113',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=400&h=300&fit=crop',
                'google_rating' => 4.4,
                'google_review_count' => 1230,
                'yelp_rating' => 4.3,
                'yelp_review_count' => 980,
                'popular_times_avg_busyness' => 58.20,
                'popularity_score' => 0.7234,
                'is_active' => true,
                'cuisines' => ['spanish'],
            ],
            // European - Greek
            [
                'name' => 'Aegean Taverna',
                'slug' => 'aegean-taverna',
                'description' => 'Traditional Greek dishes with grilled lamb, fresh gyro, spanakopita, and baklava.',
                'address' => '321 Polk St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94102',
                'latitude' => 37.7850,
                'longitude' => -122.4180,
                'phone' => '(415) 555-0114',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=300&fit=crop',
                'google_rating' => 4.3,
                'google_review_count' => 890,
                'yelp_rating' => 4.2,
                'yelp_review_count' => 720,
                'popular_times_avg_busyness' => 45.30,
                'popularity_score' => 0.6123,
                'is_active' => true,
                'cuisines' => ['greek'],
            ],
            // Latin American - Mexican
            [
                'name' => 'El Camino Real Taqueria',
                'slug' => 'el-camino-real-taqueria',
                'description' => 'Mission-style burritos, street tacos, and homemade salsas since 1992.',
                'address' => '567 Mission St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94105',
                'latitude' => 37.7876,
                'longitude' => -122.3986,
                'phone' => '(415) 555-0115',
                'price_range' => '$',
                'photo_url' => 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop',
                'google_rating' => 4.5,
                'google_review_count' => 4560,
                'yelp_rating' => 4.4,
                'yelp_review_count' => 3890,
                'popular_times_avg_busyness' => 80.60,
                'popularity_score' => 0.9345,
                'is_active' => true,
                'cuisines' => ['mexican'],
            ],
            [
                'name' => 'Casa Oaxaca',
                'slug' => 'casa-oaxaca',
                'description' => 'Regional Oaxacan cuisine with mole negro, tlayudas, mezcal cocktails, and chapulines.',
                'address' => '234 24th St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94110',
                'latitude' => 37.7525,
                'longitude' => -122.4196,
                'phone' => '(415) 555-0116',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&h=300&fit=crop',
                'google_rating' => 4.7,
                'google_review_count' => 1890,
                'yelp_rating' => 4.6,
                'yelp_review_count' => 1540,
                'popular_times_avg_busyness' => 71.20,
                'popularity_score' => 0.8678,
                'is_active' => true,
                'cuisines' => ['mexican'],
            ],
            // Latin American - Brazilian
            [
                'name' => 'Churrascaria Brasil',
                'slug' => 'churrascaria-brasil',
                'description' => 'All-you-can-eat Brazilian steakhouse with rodizio-style service, feijoada, and caipirinhas.',
                'address' => '789 Howard St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94103',
                'latitude' => 37.7830,
                'longitude' => -122.3960,
                'phone' => '(415) 555-0117',
                'price_range' => '$$$$',
                'photo_url' => 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop',
                'google_rating' => 4.4,
                'google_review_count' => 1120,
                'yelp_rating' => 4.3,
                'yelp_review_count' => 890,
                'popular_times_avg_busyness' => 56.80,
                'popularity_score' => 0.7012,
                'is_active' => true,
                'cuisines' => ['brazilian'],
            ],
            // Middle Eastern - Lebanese
            [
                'name' => 'Beirut Garden',
                'slug' => 'beirut-garden',
                'description' => 'Fresh Lebanese mezze platters, shawarma wraps, falafel, and baklava with mint lemonade.',
                'address' => '456 Market St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94105',
                'latitude' => 37.7895,
                'longitude' => -122.3995,
                'phone' => '(415) 555-0118',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1544250634-8a2476ea7817?w=400&h=300&fit=crop',
                'google_rating' => 4.5,
                'google_review_count' => 1560,
                'yelp_rating' => 4.4,
                'yelp_review_count' => 1280,
                'popular_times_avg_busyness' => 54.60,
                'popularity_score' => 0.7654,
                'is_active' => true,
                'cuisines' => ['lebanese'],
            ],
            // American - Southern
            [
                'name' => 'Southern Comfort Kitchen',
                'slug' => 'southern-comfort-kitchen',
                'description' => 'Nashville hot chicken, shrimp and grits, buttermilk biscuits, and banana pudding.',
                'address' => '901 Hayes St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94117',
                'latitude' => 37.7760,
                'longitude' => -122.4330,
                'phone' => '(415) 555-0119',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&h=300&fit=crop',
                'google_rating' => 4.6,
                'google_review_count' => 2340,
                'yelp_rating' => 4.5,
                'yelp_review_count' => 1920,
                'popular_times_avg_busyness' => 70.40,
                'popularity_score' => 0.8567,
                'is_active' => true,
                'cuisines' => ['southern'],
            ],
            // American - BBQ
            [
                'name' => 'Smoke & Oak BBQ',
                'slug' => 'smoke-and-oak-bbq',
                'description' => 'Low-and-slow Texas-style brisket, pulled pork, ribs, and craft beer on tap.',
                'address' => '321 Divisadero St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94117',
                'latitude' => 37.7720,
                'longitude' => -122.4390,
                'phone' => '(415) 555-0120',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400&h=300&fit=crop',
                'google_rating' => 4.7,
                'google_review_count' => 2890,
                'yelp_rating' => 4.6,
                'yelp_review_count' => 2340,
                'popular_times_avg_busyness' => 74.90,
                'popularity_score' => 0.9123,
                'is_active' => true,
                'cuisines' => ['bbq'],
            ],
            // American - New American
            [
                'name' => 'The Farmhouse',
                'slug' => 'the-farmhouse',
                'description' => 'Farm-to-table New American cuisine with seasonal tasting menus and craft cocktails.',
                'address' => '567 Fell St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94117',
                'latitude' => 37.7750,
                'longitude' => -122.4270,
                'phone' => '(415) 555-0121',
                'price_range' => '$$$$',
                'photo_url' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
                'google_rating' => 4.8,
                'google_review_count' => 1980,
                'yelp_rating' => 4.7,
                'yelp_review_count' => 1650,
                'popular_times_avg_busyness' => 66.70,
                'popularity_score' => 0.8912,
                'is_active' => true,
                'cuisines' => ['new-american'],
            ],
            // African - Ethiopian
            [
                'name' => 'Addis Ababa Kitchen',
                'slug' => 'addis-ababa-kitchen',
                'description' => 'Traditional Ethiopian injera with doro wat, misir wot, and kitfo served communally.',
                'address' => '789 Haight St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94117',
                'latitude' => 37.7710,
                'longitude' => -122.4350,
                'phone' => '(415) 555-0122',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop',
                'google_rating' => 4.4,
                'google_review_count' => 870,
                'yelp_rating' => 4.3,
                'yelp_review_count' => 690,
                'popular_times_avg_busyness' => 42.10,
                'popularity_score' => 0.5890,
                'is_active' => true,
                'cuisines' => ['ethiopian'],
            ],
            // Caribbean - Jamaican
            [
                'name' => 'Island Spice Jamaican Grill',
                'slug' => 'island-spice-jamaican-grill',
                'description' => 'Authentic jerk chicken, oxtail, curry goat, and plantains with fresh tropical juices.',
                'address' => '234 Fillmore St',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94117',
                'latitude' => 37.7735,
                'longitude' => -122.4305,
                'phone' => '(415) 555-0123',
                'price_range' => '$$',
                'photo_url' => 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400&h=300&fit=crop',
                'google_rating' => 4.3,
                'google_review_count' => 760,
                'yelp_rating' => 4.2,
                'yelp_review_count' => 620,
                'popular_times_avg_busyness' => 40.50,
                'popularity_score' => 0.5567,
                'is_active' => true,
                'cuisines' => ['jamaican'],
            ],
        ];
    }
}
